Lmod has detected the following error: The following module(s) are unknown: "anaconda3"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "anaconda3"

Also make sure that all modulefiles written in TCL start with the string #%Module



Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/home/oliven/scFoundationModels/notebooks/reprogramming/kmeans_clustering_n_9_20.py", line 16, in <module>
    adata = sc.read('your_data.h5ad')  # Adjust as necessary
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/legacy_api_wrap/__init__.py", line 80, in fn_compatible
    return fn(*args_all, **kw)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 129, in read
    return _read(
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/scanpy/readwrite.py", line 764, in _read
    return read_h5ad(filename, backed=backed)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 237, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/oliven/miniconda3/envs/geneformer2/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'your_data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
